# Generated by Django 5.0.7 on 2024-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='task_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
