# Generated by Django 5.0.7 on 2024-09-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasklist_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_id',
        ),
    ]
