# Generated by Django 5.0.7 on 2024-09-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tasklist_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='task_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
